
#define CRQ_GUI_CTRL CRQ_DisplayCtrl
#define CRQ_GUI_CTRL_DESKTOP CRQ_GUI_CTRL##Desktop
#define CRQ_GUI_CTRL_TITLE CRQ_GUI_CTRL##Title
#define CRQ_GUI_CTRL_CANCEL CRQ_GUI_CTRL##Cancel
#define CRQ_GUI_CTRL_CLIENT CRQ_GUI_CTRL##Client
#define CRQ_GUI_CTRL_TASK CRQ_GUI_CTRL##Task
#define CRQ_GUI_CTRL_MAP CRQ_GUI_CTRL##Map
#define CRQ_GUI_CTRL_LIST CRQ_GUI_CTRL##List
#define CRQ_GUI_CTRL_LISTMAX CRQ_GUI_CTRL##Listmax
#define CRQ_GUI_CTRL_OK CRQ_GUI_CTRL##OK
#define CRQ_GUI_CTRL_EXIT CRQ_GUI_CTRL##Exit
#define CRQ_GUI_CTRL_TEXT CRQ_GUI_CTRL##Text
#define CRQ_GUI_CTRL_TILE_0 CRQ_GUI_CTRL##Tile0
#define CRQ_GUI_CTRL_TILE_1 CRQ_GUI_CTRL##Tile1
#define CRQ_GUI_CTRL_TILE_2 CRQ_GUI_CTRL##Tile2
#define CRQ_GUI_CTRL_TILE_3 CRQ_GUI_CTRL##Tile3
#define CRQ_GUI_CTRL_TILE_4 CRQ_GUI_CTRL##Tile4
#define CRQ_GUI_CTRL_TILE_5 CRQ_GUI_CTRL##Tile5
#define CRQ_GUI_CTRL_TILE_6 CRQ_GUI_CTRL##Tile6
#define CRQ_GUI_CTRL_TILE_7 CRQ_GUI_CTRL##Tile7
#define CRQ_GUI_CTRL_TILE_8 CRQ_GUI_CTRL##Tile8
#define CRQ_GUI_CTRL_TILE_9 CRQ_GUI_CTRL##Tile9
#define CRQ_GUI_CTRL_TILE_10 CRQ_GUI_CTRL##Tile10
#define CRQ_GUI_CTRL_TILE_11 CRQ_GUI_CTRL##Tile11
#define CRQ_GUI_CTRL_TILE_12 CRQ_GUI_CTRL##Tile12
#define CRQ_GUI_CTRL_TILE_13 CRQ_GUI_CTRL##Tile13
#define CRQ_GUI_CTRL_TILE_14 CRQ_GUI_CTRL##Tile14
#define CRQ_GUI_CTRL_TILE_15 CRQ_GUI_CTRL##Tile15

#define CRQ_GUI_DISP_LAPTOP_ROOT CRQ_DisplayLaptop
#define CRQ_GUI_DISP_LAPTOP_DESKTOP CRQ_GUI_DISP_LAPTOP_ROOT##Desktop
#define CRQ_GUI_DISP_LAPTOP_TASKBAR CRQ_GUI_DISP_LAPTOP_ROOT##Taskbar
#define CRQ_GUI_DISP_LAPTOP_TILE_0 CRQ_GUI_DISP_LAPTOP_ROOT##Tile0
#define CRQ_GUI_DISP_LAPTOP_TILE_1 CRQ_GUI_DISP_LAPTOP_ROOT##Tile1
#define CRQ_GUI_DISP_LAPTOP_TILE_2 CRQ_GUI_DISP_LAPTOP_ROOT##Tile2
#define CRQ_GUI_DISP_LAPTOP_TILE_3 CRQ_GUI_DISP_LAPTOP_ROOT##Tile3
#define CRQ_GUI_DISP_LAPTOP_TILE_4 CRQ_GUI_DISP_LAPTOP_ROOT##Tile4
#define CRQ_GUI_DISP_LAPTOP_TILE_5 CRQ_GUI_DISP_LAPTOP_ROOT##Tile5
#define CRQ_GUI_DISP_LAPTOP_TILE_6 CRQ_GUI_DISP_LAPTOP_ROOT##Tile6
#define CRQ_GUI_DISP_LAPTOP_TILE_7 CRQ_GUI_DISP_LAPTOP_ROOT##Tile7
#define CRQ_GUI_DISP_LAPTOP_TILE_8 CRQ_GUI_DISP_LAPTOP_ROOT##Tile8
#define CRQ_GUI_DISP_LAPTOP_TILE_9 CRQ_GUI_DISP_LAPTOP_ROOT##Tile9
#define CRQ_GUI_DISP_LAPTOP_TILE_10 CRQ_GUI_DISP_LAPTOP_ROOT##Tile10
#define CRQ_GUI_DISP_LAPTOP_TILE_11 CRQ_GUI_DISP_LAPTOP_ROOT##Tile11
#define CRQ_GUI_DISP_LAPTOP_TILE_12 CRQ_GUI_DISP_LAPTOP_ROOT##Tile12
#define CRQ_GUI_DISP_LAPTOP_TILE_13 CRQ_GUI_DISP_LAPTOP_ROOT##Tile13
#define CRQ_GUI_DISP_LAPTOP_TILE_14 CRQ_GUI_DISP_LAPTOP_ROOT##Tile14
#define CRQ_GUI_DISP_LAPTOP_TILE_15 CRQ_GUI_DISP_LAPTOP_ROOT##Tile15

#define CRQ_GUI_DISP_MAP_ROOT CRQ_DisplayMap
#define CRQ_GUI_DISP_MAP_TITLE CRQ_GUI_DISP_MAP_ROOT##Title
#define CRQ_GUI_DISP_MAP_MAP CRQ_GUI_DISP_MAP_ROOT##Map
#define CRQ_GUI_DISP_MAP_CANCEL CRQ_GUI_DISP_MAP_ROOT##Cancel
#define CRQ_GUI_DISP_MAP_OK CRQ_GUI_DISP_MAP_ROOT##OK
#define CRQ_GUI_DISP_MAP_LIST CRQ_GUI_DISP_MAP_ROOT##List

#define CRQ_GUI_ID_ROOT 13337

#define CRQ_GUI_ID_LAPTOP_ROOT (CRQ_GUI_ID_ROOT + 1)
#define CRQ_GUI_ID_LAPTOP_DESKTOP (CRQ_GUI_ID_ROOT + 2)
#define CRQ_GUI_ID_LAPTOP_TASKBAR (CRQ_GUI_ID_ROOT + 3)
#define CRQ_GUI_ID_LAPTOP_TILE_0 (CRQ_GUI_ID_ROOT + 4)
#define CRQ_GUI_ID_LAPTOP_TILE_1 (CRQ_GUI_ID_ROOT + 5)
#define CRQ_GUI_ID_LAPTOP_TILE_2 (CRQ_GUI_ID_ROOT + 6)
#define CRQ_GUI_ID_LAPTOP_TILE_3 (CRQ_GUI_ID_ROOT + 7)
#define CRQ_GUI_ID_LAPTOP_TILE_4 (CRQ_GUI_ID_ROOT + 8)
#define CRQ_GUI_ID_LAPTOP_TILE_5 (CRQ_GUI_ID_ROOT + 9)
#define CRQ_GUI_ID_LAPTOP_TILE_6 (CRQ_GUI_ID_ROOT + 10)
#define CRQ_GUI_ID_LAPTOP_TILE_7 (CRQ_GUI_ID_ROOT + 11)
#define CRQ_GUI_ID_LAPTOP_TILE_8 (CRQ_GUI_ID_ROOT + 12)
#define CRQ_GUI_ID_LAPTOP_TILE_9 (CRQ_GUI_ID_ROOT + 13)
#define CRQ_GUI_ID_LAPTOP_TILE_10 (CRQ_GUI_ID_ROOT + 14)
#define CRQ_GUI_ID_LAPTOP_TILE_11 (CRQ_GUI_ID_ROOT + 15)
#define CRQ_GUI_ID_LAPTOP_TILE_12 (CRQ_GUI_ID_ROOT + 16)
#define CRQ_GUI_ID_LAPTOP_TILE_13 (CRQ_GUI_ID_ROOT + 17)
#define CRQ_GUI_ID_LAPTOP_TILE_14 (CRQ_GUI_ID_ROOT + 18)
#define CRQ_GUI_ID_LAPTOP_TILE_15 (CRQ_GUI_ID_ROOT + 19)

#define CRQ_GUI_ID_MAP_ROOT (CRQ_GUI_ID_ROOT + 20)
#define CRQ_GUI_ID_MAP_TITLE (CRQ_GUI_ID_ROOT + 21)
#define CRQ_GUI_ID_MAP_MAP (CRQ_GUI_ID_ROOT + 22)
#define CRQ_GUI_ID_MAP_CANCEL (CRQ_GUI_ID_ROOT + 23)
#define CRQ_GUI_ID_MAP_OK (CRQ_GUI_ID_ROOT + 24)
#define CRQ_GUI_ID_MAP_LIST (CRQ_GUI_ID_ROOT + 25)
