

#define CRQ_UI_ID_ROOT 13337
#define CRQ_UI_ID_HUD (CRQ_UI_ID_ROOT + 1024)
#define CRQ_UI_ID_USER (CRQ_UI_ID_ROOT + 4096)
// NOTE TO SELF: Using __LINE__ does not seem to be reliable here...
// TODO: try __COUNTER__ and __COUNTER_RESET__ instead (since v2.02)
// NOTE TO SELF: I'll need to somehow "rasterize" __COUNTER__, which I had already tried with __LINE__
// NOTE TO SELF: Just put it in the .ods as well, finally, ffs
#define CRQ_UI_ID_LAPTOP_ROOT (CRQ_UI_ID_ROOT + 1)
#define CRQ_UI_ID_LAPTOP_DESKTOP (CRQ_UI_ID_ROOT + 2)
#define CRQ_UI_ID_LAPTOP_TASKBAR (CRQ_UI_ID_ROOT + 3)
#define CRQ_UI_ID_LAPTOP_TILE_0 (CRQ_UI_ID_ROOT + 4)
#define CRQ_UI_ID_LAPTOP_TILE_1 (CRQ_UI_ID_ROOT + 5)
#define CRQ_UI_ID_LAPTOP_TILE_2 (CRQ_UI_ID_ROOT + 6)
#define CRQ_UI_ID_LAPTOP_TILE_3 (CRQ_UI_ID_ROOT + 7)
#define CRQ_UI_ID_LAPTOP_TILE_4 (CRQ_UI_ID_ROOT + 8)
#define CRQ_UI_ID_LAPTOP_TILE_5 (CRQ_UI_ID_ROOT + 9)
#define CRQ_UI_ID_LAPTOP_TILE_6 (CRQ_UI_ID_ROOT + 10)
#define CRQ_UI_ID_LAPTOP_TILE_7 (CRQ_UI_ID_ROOT + 11)
#define CRQ_UI_ID_LAPTOP_TILE_8 (CRQ_UI_ID_ROOT + 12)
#define CRQ_UI_ID_LAPTOP_TILE_9 (CRQ_UI_ID_ROOT + 13)
#define CRQ_UI_ID_LAPTOP_TILE_10 (CRQ_UI_ID_ROOT + 14)
#define CRQ_UI_ID_LAPTOP_TILE_11 (CRQ_UI_ID_ROOT + 15)
#define CRQ_UI_ID_LAPTOP_TILE_12 (CRQ_UI_ID_ROOT + 16)
#define CRQ_UI_ID_LAPTOP_TILE_13 (CRQ_UI_ID_ROOT + 17)
#define CRQ_UI_ID_LAPTOP_TILE_14 (CRQ_UI_ID_ROOT + 18)
#define CRQ_UI_ID_LAPTOP_TILE_15 (CRQ_UI_ID_ROOT + 19)
#define CRQ_UI_ID_MAP_ROOT (CRQ_UI_ID_ROOT + 20)
#define CRQ_UI_ID_MAP_TITLE (CRQ_UI_ID_ROOT + 21)
#define CRQ_UI_ID_MAP_MAP (CRQ_UI_ID_ROOT + 22)
#define CRQ_UI_ID_MAP_CANCEL (CRQ_UI_ID_ROOT + 23)
#define CRQ_UI_ID_MAP_OK (CRQ_UI_ID_ROOT + 24)
#define CRQ_UI_ID_MAP_LIST (CRQ_UI_ID_ROOT + 25)
#define CRQ_UI_ID_MAP_INFO (CRQ_UI_ID_ROOT + 26)
#define CRQ_UI_ID_INFO_DESC (CRQ_UI_ID_ROOT + 27)
#define CRQ_UI_ID_INFO_PROG (CRQ_UI_ID_ROOT + 28)

#define CRQ_HUD_ID_ROOT (CRQ_UI_ID_HUD + 1)
