
#define CRQ_CRC_MODULO 65536

#define CRQ_WAIT_RESOLUTION 0.15

#define CRQ_POS_ABS 0
#define CRQ_POS_REL 1
#define CRQ_POS_VEC 2
#define CRQ_POS_VECZ 3
#define CRQ_POS_FIND 4
#define CRQ_POS_EMPTY 5
#define CRQ_POS_UTIL_RADIUS 50
#define CRQ_POS_UTIL_RESOLUTION 5

#define CRQ_VEC_UTIL_RADIUS CRQ_POS_UTIL_RADIUS
#define CRQ_VEC_UTIL_RESOLUTION CRQ_POS_UTIL_RESOLUTION
#define CRQ_VEC_ABS 10
#define CRQ_VEC_REL 11
#define CRQ_VEC_VEC 12
#define CRQ_VEC_VECZ 13
#define CRQ_VEC_FIND 15
#define CRQ_VEC_HOUSE 16

#define CRQ_CENTER_OFFSET_TOLERANCE 0.05

#define CRQ_CLUTTER_EXTRA 50

#define CRQ_TIME_DAWN_MIN 6.25
#define CRQ_TIME_DAWN_MAX 7
#define CRQ_TIME_MORNING_MIN 7
#define CRQ_TIME_MORNING_MAX 11
#define CRQ_TIME_NOON_MIN 11
#define CRQ_TIME_NOON_MAX 14
#define CRQ_TIME_AFTERNOON_MIN 14
#define CRQ_TIME_AFTERNOON_MAX 17
#define CRQ_TIME_EVENING_MIN 17
#define CRQ_TIME_EVENING_MAX 18.75
#define CRQ_TIME_NIGHT_MIN 18.75
#define CRQ_TIME_NIGHT_MAX 6.25

#define CRQ_SIDE_UNKNOWN -1
#define CRQ_SIDE_BLUFOR 0
#define CRQ_SIDE_IDFOR 1
#define CRQ_SIDE_OPFOR 2
#define CRQ_SIDE_CIVFOR 3
//#define CRQ_SIDES [CRQ_SIDE_BLUFOR,CRQ_SIDE_IDFOR,CRQ_SIDE_OPFOR,CRQ_SIDE_CIVFOR]

#define CRQ_GROUP_FORMATION ["COLUMN","STAG COLUMN","WEDGE","ECH LEFT","ECH RIGHT","VEE","LINE","FILE","DIAMOND"]
