
#define CRQ_AI_SCRIPT_SOURCE "CRQ\CRQ_AI_Script.sqf " // MUST INCLUDE TRAILING WHITESPACE!

#define CRQ_AI_SCRIPT_RESTART -1
#define CRQ_AI_SCRIPT_WAIT 0
#define CRQ_AI_SCRIPT_REGROUP 1
#define CRQ_AI_SCRIPT_SCATTER 2
#define CRQ_AI_SCRIPT_REST 3
#define CRQ_AI_SCRIPT_STOP 4
#define CRQ_AI_SCRIPT_LOOK 5
#define CRQ_AI_SCRIPT_BINO 6
#define CRQ_AI_SCRIPT_RETURN 7

#define CRQ_AI_FORM_COLUMN 1
#define CRQ_AI_FORM_STAG_COLUMN 2
#define CRQ_AI_FORM_WEDGE 3
#define CRQ_AI_FORM_ECH_LEFT 4
#define CRQ_AI_FORM_ECH_RIGHT 5
#define CRQ_AI_FORM_ECH_VEE 6
#define CRQ_AI_FORM_LINE 7
#define CRQ_AI_FORM_FILE 8
#define CRQ_AI_FORM_DIAMOND 9

#define CRQ_AI_MODE_STEALTH 1
#define CRQ_AI_MODE_COMBAT 2
#define CRQ_AI_MODE_AWARE 3
#define CRQ_AI_MODE_SAFE 4
#define CRQ_AI_MODE_CARELESS 5

#define CRQ_AI_SPEED_NORMAL 1
#define CRQ_AI_SPEED_FULL 2
#define CRQ_AI_SPEED_LIMITED 3

#define CRQ_AI_RADIUS_MOVE_INFANTRY 3
#define CRQ_AI_RADIUS_MOVE_VEHICLE 24

#define CRQ_AI_PATTERN_GARRISON [\
[CRQ_AI_SCRIPT_SCATTER,CRQ_AI_SCRIPT_WAIT,CRQ_AI_SCRIPT_REST,CRQ_AI_SCRIPT_WAIT,CRQ_AI_SCRIPT_REST,CRQ_AI_SCRIPT_WAIT,CRQ_AI_SCRIPT_RETURN,CRQ_AI_SCRIPT_REGROUP]]

#define CRQ_AI_PATTERN_SPOT [\
[CRQ_AI_SCRIPT_LOOK,CRQ_AI_SCRIPT_RESTART]]

#define CRQ_AI_PATTERN_PATROL [\
[CRQ_AI_SCRIPT_WAIT,CRQ_AI_SCRIPT_SCATTER,CRQ_AI_SCRIPT_SCATTER,CRQ_AI_SCRIPT_REGROUP],\
[CRQ_AI_SCRIPT_SCATTER,CRQ_AI_SCRIPT_REST,CRQ_AI_SCRIPT_REGROUP],\
[CRQ_AI_SCRIPT_WAIT,CRQ_AI_SCRIPT_WAIT,CRQ_AI_SCRIPT_REGROUP],\
[CRQ_AI_SCRIPT_WAIT,CRQ_AI_SCRIPT_REST,CRQ_AI_SCRIPT_REST,CRQ_AI_SCRIPT_REGROUP],\
[CRQ_AI_SCRIPT_SCATTER,CRQ_AI_SCRIPT_SCATTER,CRQ_AI_SCRIPT_SCATTER,CRQ_AI_SCRIPT_REGROUP]]

#define CRQ_AI_PATTERN_VEHICLE [\
[CRQ_AI_SCRIPT_WAIT,CRQ_AI_SCRIPT_WAIT,CRQ_AI_SCRIPT_WAIT],\
[CRQ_AI_SCRIPT_WAIT,CRQ_AI_SCRIPT_WAIT],\
[CRQ_AI_SCRIPT_WAIT]]
