
#define CRQ_PVAR_LINK "CRQ_PVAR_000"

#ifdef CRQ_DEFINE_CLIENT
#define CRQ_CVAR_CLIENT_SPAWN "CRQ_CVAR_000"
#endif

#ifdef CRQ_DEFINE_SERVER
#define CRQ_SVAR_CORPSE_EXPEDITE "CRQ_SVAR_000"
#endif
