
#define CRQ_CLIENT_WAIT_RESOLUTION 0.15

#define CRQ_SPAWN_RESOLVE_TIMEOUT 4
#define CRQ_SPAWN_RESOLVE_DELAY 0.05
#define CRQ_SPAWN_UNRESOLVED_TIMEOUT 24
#define CRQ_SPAWN_UNRESOLVED_DELAY 1
#define CRQ_SPAWN_FADEIN_TIME 4
#define CRQ_SPAWN_HOLD_TIME 0.5
