
#define CQM_GUI_COLOR_TITLE {0.0,0.0,0.0,1.0}
#define CQM_GUI_COLOR_CLIENT {0.15,0.15,0.15,0.75}
#define CQM_GUI_COLOR_TASK {0.05,0.05,0.05,1.0}

#define CQM_GUI_IMG_LAPTOP_DESKTOP "res\ui\Desktop.paa"

#define CQM_GUI_IMG_LAPTOP_TILE_0 ""
#define CQM_GUI_IMG_LAPTOP_TILE_1 ""
#define CQM_GUI_IMG_LAPTOP_TILE_2 "res\ui\ButtonMail.paa"
#define CQM_GUI_IMG_LAPTOP_TILE_3 "res\ui\ButtonWeb.paa"
#define CQM_GUI_IMG_LAPTOP_TILE_4 ""
#define CQM_GUI_IMG_LAPTOP_TILE_5 ""
#define CQM_GUI_IMG_LAPTOP_TILE_6 ""
#define CQM_GUI_IMG_LAPTOP_TILE_7 "res\ui\ButtonInfo.paa"
#define CQM_GUI_IMG_LAPTOP_TILE_8 "res\ui\ButtonCash.paa"
#define CQM_GUI_IMG_LAPTOP_TILE_9 "res\ui\ButtonTeam.paa"
#define CQM_GUI_IMG_LAPTOP_TILE_10 ""
#define CQM_GUI_IMG_LAPTOP_TILE_11 ""
#define CQM_GUI_IMG_LAPTOP_TILE_12 ""
#define CQM_GUI_IMG_LAPTOP_TILE_13 "res\ui\ButtonSettings.paa"
#define CQM_GUI_IMG_LAPTOP_TILE_14 ""
#define CQM_GUI_IMG_LAPTOP_TILE_15 "res\ui\ButtonPower.paa"

#define CQM_GUI_TIP_LAPTOP_TILE_0 ""
#define CQM_GUI_TIP_LAPTOP_TILE_1 ""
#define CQM_GUI_TIP_LAPTOP_TILE_2 "E-Mail"
#define CQM_GUI_TIP_LAPTOP_TILE_3 "Web Browser"
#define CQM_GUI_TIP_LAPTOP_TILE_4 ""
#define CQM_GUI_TIP_LAPTOP_TILE_5 ""
#define CQM_GUI_TIP_LAPTOP_TILE_6 ""
#define CQM_GUI_TIP_LAPTOP_TILE_7 "Campaign Overview"
#define CQM_GUI_TIP_LAPTOP_TILE_8 "Finances"
#define CQM_GUI_TIP_LAPTOP_TILE_9 "Team"
#define CQM_GUI_TIP_LAPTOP_TILE_10 ""
#define CQM_GUI_TIP_LAPTOP_TILE_11 ""
#define CQM_GUI_TIP_LAPTOP_TILE_12 ""
#define CQM_GUI_TIP_LAPTOP_TILE_13 "Settings"
#define CQM_GUI_TIP_LAPTOP_TILE_14 ""
#define CQM_GUI_TIP_LAPTOP_TILE_15 "Shut Down"
