
#define CRA_GUI_DISP_MAIL_ROOT CRA_DisplayMail
#define CRA_GUI_DISP_MAIL_TITLE CRA_GUI_DISP_MAIL_ROOT##Title
#define CRA_GUI_DISP_MAIL_CLIENT CRA_GUI_DISP_MAIL_ROOT##Client
#define CRA_GUI_DISP_MAIL_CANCEL CRA_GUI_DISP_MAIL_ROOT##Cancel
#define CRA_GUI_DISP_MAIL_LIST CRA_GUI_DISP_MAIL_ROOT##List

#define CRA_GUI_DISP_MESSAGE_ROOT CRA_DisplayMessage
#define CRA_GUI_DISP_MESSAGE_TITLE CRA_GUI_DISP_MESSAGE_ROOT##Title
#define CRA_GUI_DISP_MESSAGE_CLIENT CRA_GUI_DISP_MESSAGE_ROOT##Client
#define CRA_GUI_DISP_MESSAGE_CANCEL CRA_GUI_DISP_MESSAGE_ROOT##Cancel
#define CRA_GUI_DISP_MESSAGE_LIST CRA_GUI_DISP_MESSAGE_ROOT##List
#define CRA_GUI_DISP_MESSAGE_TEXT CRA_GUI_DISP_MESSAGE_ROOT##Text

#define CRA_GUI_ID_ROOT 31337

#define CRA_GUI_ID_MAIL_ROOT (CRA_GUI_ID_ROOT + 1)
#define CRA_GUI_ID_MAIL_TITLE (CRA_GUI_ID_ROOT + 2)
#define CRA_GUI_ID_MAIL_CLIENT (CRA_GUI_ID_ROOT + 3)
#define CRA_GUI_ID_MAIL_CANCEL (CRA_GUI_ID_ROOT + 4)
#define CRA_GUI_ID_MAIL_LIST (CRA_GUI_ID_ROOT + 5)
#define CRA_GUI_ID_MESSAGE_ROOT (CRA_GUI_ID_ROOT + 6)
#define CRA_GUI_ID_MESSAGE_TITLE (CRA_GUI_ID_ROOT + 7)
#define CRA_GUI_ID_MESSAGE_CLIENT (CRA_GUI_ID_ROOT + 8)
#define CRA_GUI_ID_MESSAGE_CANCEL (CRA_GUI_ID_ROOT + 9)
#define CRA_GUI_ID_MESSAGE_LIST (CRA_GUI_ID_ROOT + 10)
#define CRA_GUI_ID_MESSAGE_TEXT (CRA_GUI_ID_ROOT + 11)
