
#define CRA_LOAD_NEXT(INDEX,TOTAL) pRA_LoadMessage = pRA_LoadMessage + 1; pRA_LoadIndex = INDEX; pRA_LoadTotal = TOTAL;
#define CRA_LOAD_INDEX(INDEX) pRA_LoadIndex = INDEX;
#define CRA_LOAD_INCREMENT() pRA_LoadIndex = pRA_LoadIndex + 1;

#define CRA_SCRIPT_TIMEOUT 8000 // TODO wait, what? 8 THOUSAND seconds?

#define CRA_ACTIVITY_COEF 1
#define CRA_ACTIVITY_MIN 0
#define CRA_ACTIVITY_MAX 120
#define CRA_ACTIVITY_HYSTERESIS 0
#define CRA_ACTIVITY_BASE(DIST) ((((DIST) - CRA_ACTIVITY_HYSTERESIS) + (((DIST) + CRA_ACTIVITY_HYSTERESIS)^2 + 4 * (DIST)^2)^0.5) * 0.5)

#define CRA_STATE_INIT 0
#define CRA_STATE_ACTIVE 1
#define CRA_STATE_HIBERNATE 2

#define CRA_MARKER_ALPHA [0.33,1.00,0.33]
#define CRA_MARKER_UNKNOWN "mil_unknown_noShadow"

//#define CRA_PATHGENERATOR_RADIUS 250
#define CRA_PATHGENERATOR_RADIUS 0.35

#define CRA_ACTION_PRIORITY 1.0
#define CRA_ACTION_RANGE 3.0
#define CRA_ACTION_COLOR "FCD937"
#define CRA_ACTION_ID_PLAYER_TELEPORT 1
#define CRA_ACTION_ID_PLAYER_PARADROP 2
#define CRA_ACTION_ID_MILITIA_TRAIN 21
#define CRA_ACTION_ID_INVENTORY_SORT 31
#define CRA_ACTION_ID_INVENTORY_GATHER 32
#define CRA_ACTION_ID_INTEL_GATHER 41

#define CRA_PLAYER_SIDE CRQ_SD_BLU // Not yet fully implemented
#define CRA_PLAYER_VAR "gU_Player_"
#define CRA_PLAYER_IDENTITY [\
["GreekHead_A3_11","Male04ENGB",["Craq","",""],"",1],\
["AsianHead_A3_03","Male02ENGB",["Tung","",""],"",1],\
["WhiteHead_10","Male07ENG",["Martinez","",""],"",1],\
["PersianHead_A3_03","Male08ENG",["Rabet","",""],"",1],\
["AfricanHead_02","Male02ENGFRE",["Hasan","",""],"",1],\
["PersianHead_A3_02","Male01ENGFRE",["Jalali","",""],"",1],\
["WhiteHead_20","Male05ENGB",["Walsh","",""],"",1],\
["GreekHead_A3_03","Male02GRE",["Constantinou","",""],"",1]]

#define CRA_CIVILIAN_SPAWN_TIMER 6
#define CRA_CIVILIAN_SPAWN_CLEARANCE 25
#define CRA_CIVILIAN_ALTITUDE_WING 450
#define CRA_CIVILIAN_ALTITUDE_ROTOR 150
#define CRA_CIVILIAN_EXTEND 250
#define CRA_CIVILIAN_EXTENSIONS [400,200,100,50]

#define CRA_GP_T_GUARD 0
#define CRA_GP_T_SPOT 1
#define CRA_GP_T_PATROL 2
#define CRA_GP_T_VEHICLE 3
#define CRA_GP_T_STATIC 4

/*
#define CRA_STRENGTH_GUARD 8
#define CRA_STRENGTH_SPOT 1
#define CRA_STRENGTH_PATROL 4
*/

#define CRA_STRENGTH [8,1,4]

#define CRA_PERSONNEL_TYPES [\
[CRA_GP_T_GUARD,-1,[CRA_SQUAD_TYPE_BASIC]],\
[CRA_GP_T_SPOT,-1,[CRA_SQUAD_TYPE_SPOT]],\
[CRA_GP_T_PATROL,-1,[CRA_SQUAD_TYPE_BASIC]],\
[CRA_GP_T_VEHICLE,-1,[[-1,CRA_ASSET_WHEELED,CRA_VEHICLE_ARMED]]],\
[CRA_GP_T_STATIC,-1,[CRA_STATIC_MG_HIGH]]]

#define CRA_GP_WP_GUARD [[[CRQ_VU_PREL]]]
#define CRA_GP_WP_SPOT [[[CRQ_VU_PREL]]]
#define CRA_GP_WP_PATROL [[[CRQ_VU_PFND,['houses',125]],[CRQ_VU_PEMP,[5,0,35]]],[[CRQ_VU_PFND,['meadow',125]],[CRQ_VU_PEMP,[5,0,35]]],[[CRQ_VU_PFND,['trees',125]],[CRQ_VU_PEMP,[5,0,35]]]]
#define CRA_GP_WP_PATROL_NEAR [[[CRQ_VU_PFND,['houses',75]],[CRQ_VU_PEMP,[5,0,35]]],[[CRQ_VU_PFND,['meadow',75]],[CRQ_VU_PEMP,[5,0,35]]],[[CRQ_VU_PFND,['trees',75]],[CRQ_VU_PEMP,[5,0,35]]]]
#define CRA_GP_WP_VEHICLE [[[CRQ_VU_PEMP,[15,-1,175]]],[[CRQ_VU_PEMP,[15,-1,175]]],[[CRQ_VU_PEMP,[15,-1,175]]]]
#define CRA_GP_WP_STATIC [[[CRQ_VU_PREL]]]

#define CRA_GP_WP_LOCATION [\
[CRA_GP_WP_GUARD,CRA_GP_WP_SPOT,CRA_GP_WP_PATROL,CRA_GP_WP_VEHICLE,CRA_GP_WP_STATIC],\
[CRA_GP_WP_GUARD,CRA_GP_WP_SPOT,CRA_GP_WP_PATROL,CRA_GP_WP_VEHICLE,CRA_GP_WP_STATIC],\
[CRA_GP_WP_GUARD,CRA_GP_WP_SPOT,CRA_GP_WP_PATROL,CRA_GP_WP_VEHICLE,CRA_GP_WP_STATIC],\
[CRA_GP_WP_GUARD,CRA_GP_WP_SPOT,CRA_GP_WP_PATROL,CRA_GP_WP_VEHICLE,CRA_GP_WP_STATIC],\
[CRA_GP_WP_GUARD,CRA_GP_WP_SPOT,CRA_GP_WP_PATROL,CRA_GP_WP_VEHICLE,CRA_GP_WP_STATIC],\
[CRA_GP_WP_GUARD,CRA_GP_WP_SPOT,CRA_GP_WP_PATROL_NEAR,CRA_GP_WP_VEHICLE,CRA_GP_WP_STATIC],\
[CRA_GP_WP_GUARD,CRA_GP_WP_SPOT,CRA_GP_WP_PATROL_NEAR,CRA_GP_WP_VEHICLE,CRA_GP_WP_STATIC]]



#define CRA_GV_OW_MIN 0
#define CRA_GV_OW_MAX 1
#define CRA_GV_OW_RATE_DECAY 0.1
#define CRA_GV_OW_RATE_GROWTH 0.2
#define CRA_GV_OW_FACTOR_VALUE 0.2

#define CRA_GP_TICKET_MAX 65536 // high enough to practically never collide/low enough no 1e10 collision
#define CRA_GP_TICKET_ID "CRA_GP_%1" // %1 = ticket

#define CRA_GP_TSK_AI_TIMEOUT CRA_SCRIPT_TIMEOUT
#define CRA_GP_TSK_UNKNOWN -1
#define CRA_GP_TSK_WH_CRUISE_FIND 1
#define CRA_GP_TSK_WH_CRUISE_TRVL 2
#define CRA_GP_TSK_FW_CRUISE_FIND 21
#define CRA_GP_TSK_FW_CRUISE_TRVL 22



