
#define CRA_GUI_DISP_MAIL_ROOT CRA_DisplayMail
#define CRA_GUI_DISP_MAIL_TITLE CRA_GUI_DISP_MAIL_ROOT##Title
#define CRA_GUI_DISP_MAIL_CLIENT CRA_GUI_DISP_MAIL_ROOT##Client
#define CRA_GUI_DISP_MAIL_CANCEL CRA_GUI_DISP_MAIL_ROOT##Cancel
#define CRA_GUI_DISP_MAIL_LIST CRA_GUI_DISP_MAIL_ROOT##List

#define CRA_GUI_DISP_MESSAGE_ROOT CRA_DisplayMessage
#define CRA_GUI_DISP_MESSAGE_TITLE CRA_GUI_DISP_MESSAGE_ROOT##Title
#define CRA_GUI_DISP_MESSAGE_CLIENT CRA_GUI_DISP_MESSAGE_ROOT##Client
#define CRA_GUI_DISP_MESSAGE_CANCEL CRA_GUI_DISP_MESSAGE_ROOT##Cancel
#define CRA_GUI_DISP_MESSAGE_LIST CRA_GUI_DISP_MESSAGE_ROOT##List
#define CRA_GUI_DISP_MESSAGE_TEXT CRA_GUI_DISP_MESSAGE_ROOT##Text

#define CRA_GUI_ID_MAIL_ROOT (CRQ_UI_ID_USER + 1)
#define CRA_GUI_ID_MAIL_TITLE (CRQ_UI_ID_USER + 2)
#define CRA_GUI_ID_MAIL_CLIENT (CRQ_UI_ID_USER + 3)
#define CRA_GUI_ID_MAIL_CANCEL (CRQ_UI_ID_USER + 4)
#define CRA_GUI_ID_MAIL_LIST (CRQ_UI_ID_USER + 5)
#define CRA_GUI_ID_MESSAGE_ROOT (CRQ_UI_ID_USER + 6)
#define CRA_GUI_ID_MESSAGE_TITLE (CRQ_UI_ID_USER + 7)
#define CRA_GUI_ID_MESSAGE_CLIENT (CRQ_UI_ID_USER + 8)
#define CRA_GUI_ID_MESSAGE_CANCEL (CRQ_UI_ID_USER + 9)
#define CRA_GUI_ID_MESSAGE_LIST (CRQ_UI_ID_USER + 10)
#define CRA_GUI_ID_MESSAGE_TEXT (CRQ_UI_ID_USER + 11)
